### ISSUE TITLE
logo?

### ISSUE THREAD

**Issue by yoshuawuyts** [sethvincent/virtual-app#15]
I made a logo [for mercury](https://github.com/Raynos/mercury/pull/98#issuecomment-156461863) a while back, but it doesn't look like it'll get adopted (3 months, no replies from maintainers); so if we like it and want it we could totally use it for `virtual-app`. 

Not that we _need_ a logo, but it might be fun. What do you reckon?

**tiny**
<img alt="mercury logo" height="100" style="max-width: 100%" src="https://cloud.githubusercontent.com/assets/2467194/11149253/aec2b65a-8a75-11e5-96d3-51fb2351e9fd.png">

**large**
![512](https://cloud.githubusercontent.com/assets/2467194/11149253/aec2b65a-8a75-11e5-96d3-51fb2351e9fd.png)

**Comment by sethvincent** [comment]
Cool, I like it!
