### ISSUE TITLE
universal / isomorphic

### ISSUE THREAD

**Issue by BenjaminVerble** [sethvincent/virtual-app#17]
I was attempting to set up an app that does initial render on the server. Some changes would be needed, unless I am missing something. Keeping in the spirit of composition, I would propose that virtual-app return the result of app.tree.render() (currently line 78) and allow the user to handle that dom node. I have an example working here: https://github.com/BenjaminVerble/site-starter/blob/master/app/vapp.js  

On the server, toString() is called on that result and sent as an html string
On the client, the consumer of virtual-app simply appends the result

I've taken a similar approach here and have had good results with routing: https://github.com/BenjaminVerble/universal-redux-virtual-dom

Would this be a pr you would consider?

**Comment by yoshuawuyts** [comment]
Hey, thanks for raising this. We def want to be supporting server side rendering. PR welcome!

**Comment by sethvincent** [comment]
Nice, this is something I was meaning to look at. Yeah, I think the approach you're taking in that example looks good.

**Comment by BenjaminVerble** [comment]
awesome. will have a PR up soon. thank you.

**Comment by BenjaminVerble** [comment]
adding this link for reference: [first pr to enable server-rendering](https://github.com/sethvincent/virtual-app/pull/18)
I would love to hear other people's ideas about the best way to make the api serve server-rendering in the future. Equally interested in docs, tutorials, and examples that enhance this for users.

**Comment by sethvincent** [comment]
Published #18 at v3.0.0! :tada:

**Comment by yoshuawuyts** [comment]
rad!

**Comment by BenjaminVerble** [comment]
thanks all. this is good fun

**Comment by sethvincent** [comment]
:+1: Closing this and we can make new issues for specific next steps. :beer:
