### ISSUE TITLE
errors with simple button and action

### ISSUE THREAD

**Issue by BenjaminVerble** [sethvincent/virtual-app#2]
modified your example:

getting this:

after 1 button click. works fine.
2nd click and following, 1 unique error apiece. (see image)
Not sure if I am misusing this or if there is a bug. 

Not urgent. Thanks for working on this module(s)

<img width="1076" alt="screen shot 2015-12-29 at 1 28 23 pm" src="https://cloud.githubusercontent.com/assets/3958020/12042447/208b7bd6-ae30-11e5-9e8a-36c5cf009514.png">

**Comment by sethvincent** [comment]
I just updated the example with the addition of an input field that changes the title on input: https://github.com/sethvincent/virtual-app/blob/master/example.js#L42

That might give a clue about what's happening.

Could you make a gist with your code?

**Comment by BenjaminVerble** [comment]
I apologize. I actually made a gist yesterday but forgot to add the link to the issue: https://gist.github.com/BenjaminVerble/0cc9752fa8204c42b041

**Comment by BenjaminVerble** [comment]
it was my fault, line 36 of gist. tried to pass a value and children to a v-dom/h node. closing issue. thanks for taking a look.

**Comment by sethvincent** [comment]
Cool! I was just typing something about line 36. Let me know if anything else comes up.

**Comment by BenjaminVerble** [comment]
thanks. I'm just trying to learn fp patterns for the front end after studying a bit of haskell. I was finding redux + react took a lot of brain power to get working on something practical (perhaps it's just taste). It felt like the tooling was complicated and that the composition of functions didn't make sense in all cases. I'm glad I got this "hello world" working. I'm going to build something the size of a todomvc with electron and see how it works out in practice. Thanks again for putting this module together. The api is friendly to my brain.

**Comment by sethvincent** [comment]
:+1:  What you're describing is really similar to my reasoning for working on this module. I like what's happening with react, redux, and related projects, and want to explore a simpler, functional approach.
