### ISSUE TITLE
Stand-alone components that require local state

### ISSUE THREAD

**Issue by kvnneff** [sethvincent/virtual-app#20]
This is probably outside the scope of `virtual-app` but I'm hoping maybe its users have run into the same issue and have figured something out.

I'm building an app with `virtual-app` and I have a component that, say, after a button is clicked dispatches an action that fetches data from some external api, such as github, and populates the app state with the retrieved data.  The component gets rendered again because of the state change and presents a list of options that, when clicked, perform more api calls and retrieves more data to populate the state, triggering more renders, etc.  Essentially a menu with 3 or 4 levels of options and each level requires an api call that retrieves the next list of options.

Now I want to make it a stand-alone component so that anyone else building an app with `virtual-app` or even maybe just `virtual-dom` can drop it into their app.

How do I untie it from a global app state, or make it easy to integrate into a developer's app state?  Should I just keep the state local to the component, and if so how do I let `virtual-app` know that the local state has changed and trigger an update?

Has anyone else run into this?

**Comment by kvnneff** [comment]
I just came across [this thread on Reddit](https://www.reddit.com/r/javascript/comments/2jav2q/is_there_any_good_standalone_implementation_of/) where @Raynos talks about this a little bit.  He says:

> re-usable views is as functions that return VDOMs only works for stateless views. Most views are not stateless. once you have stateful views the coupling to a framework starts to come into play.

After looking around at various options I'm tending to agree that stateful components are going to have to be coupled and aware of some sort of app/framework implementation.  My first thought is to require that `app.store` or `app.send` get passed in to a reusable component but I have a feeling this would mess with server rendering.

**Comment by yoshuawuyts** [comment]
You're right that you'd need to create a vdom specific wrapper for your component - but given that it's very light (perf overhead is a single object) it shouldn't be that bad I think.

For stateful components that exist outside the vdom loop use [virtual-widget](https://www.npmjs.com/package/virtual-widget) - this is also useful for perf sensitive components such as d3 charts and the like. For an example of this check out [virtual-streamgraph](https://github.com/yoshuawuyts/virtual-streamgraph/blob/master/index.js).

To render them on the server expose a `.render` hook on the widget (see [vdom-to-html](https://github.com/nthtran/vdom-to-html/#special-case-for-widgets)).

I hope this was helpful. Cheers!

**Comment by kvnneff** [comment]
Thanks for the tips!  I'm going to play with `virtual-widget` today and see what I can do.
