### ISSUE TITLE
idea: support yo-yo

### ISSUE THREAD

**Issue by yoshuawuyts** [sethvincent/virtual-app#22]
# idea: support yo-yo

[`yo-yo`](https://www.npmjs.com/package/yo-yo) comes in weighing [about `10KB` less than `virtual-dom`](https://twitter.com/yoshuawuyts/status/709364907674705920), and is equally flexible. In the examples it seems mostly focused on creating self-contained elements, but I don't see why it wouldn't be possible to use it as a `virtual-app` backend - which I've found to work very well for managing complexity.
## changes

Though `yo-yo` and `virtual-dom` seem mostly compatible, there are a couple of changes that should be made:
- [ ] change `app.h` from `hyperscript` to `hyperx` - the biggest and most controversial change, this could potentially warrant creating a different package instead
- [ ] loosen up `virtual-raf` to accept different diffing methods (e.g. `yo.update(old, new)`

It might be worth revisiting #3; as apparently `hyperscript` no longer is the lowest common denominator - `hyperx` appears to be closer. I quite like the idea of having a super flexible framework that only overlays a certain pattern on top of components of a choosing - I think it could definitely work for `virtual-app` without introducing too much scope creep.
## wrapping up

And that's about it I think. We're already returning a DOM node that can be appended, so that was a very good change in hindsight. Let me know what you think! :sparkles:
## see also
- https://www.npmjs.com/package/yo-yo
- https://www.npmjs.com/package/virtual-raf
- https://www.npmjs.com/package/bel
- https://www.npmjs.com/package/morphdom

**Comment by cellvia** [comment]
Don't mean to derail this, totally OK to open separate thread, but curious if you had considered snabbdom instead of virtual-dom ? It is supposedly more performant and offers more hooks and support for things like animations... Thoughts?

**Comment by yoshuawuyts** [comment]
Very interesting - just 200 lines of code is pretty cool! It looks like they're using a slightly different syntax than `virtual-dom` though. I'm starting to think that perhaps the only reasonable approach to dealing with different libraries is to have a html-as-template-literal syntax that can then be translated down to whatever engine, perhaps using compile time transforms to make it fast. Also not sure I dig the whole react / android-esque hook system.

**Comment by cellvia** [comment]
Actually now that im looking more at `yoyo`, its really exciting, and way more in line w/ my modular npm approach than snabddom.  Happen to be a max ogden fan as well so that doesnt hurt.  I'm noticing that a huge component of `yoyo` is `bel` and found this: https://github.com/shama/bel/wiki#elements-on-npmjscom  – npm-ability of components is basically what im looking for here so thats a positive sign.  i'll keep an eye out here as `virtual-app` leveraging this could be the sweet spot im looking for, and if so i may be able to get my team to contribute to the project. thanks for fielding all my questions!

**Comment by sethvincent** [comment]
:+1: I'm going to experiment with bel & yo-yo today / this week.

Getting hyperxify or a new transform working with bel/yo-yo is the only main concern I have: https://github.com/shama/bel/issues/7

**Comment by shama** [comment]
I have a transform almost ready for shama/bel#7 and the early perf and file size results look really promising.

But currently without a transform, I get very similar perf results creating trees with `virtual-dom` and `yo-yo` but the difference is, `yo-yo` has already created an element in that time where `virtual-dom` would still need to render to actual elements.

In the meantime, one could use `hyperxify` now by doing:

``` js
var createElement = require('bel').createElement
var hyperx = require('hyperx')
var yo = hyperx(createElement)
```

Then hyperxify will recognize the require to `hyperx` and replace it with calls directly to `createElement`. You get a little perf boost and support older browsers.

**Comment by sethvincent** [comment]
@shama rad! i'll watch for that transform & use the method you describe for now.

**Comment by sethvincent** [comment]
I'm leaning toward not integrating yo-yo with virtual-app, mostly because I made this tiny state module [send-action](http://github.com/sethvincent/send-action), and a usage example with it and yo-yo seems easier to reason about than virtual-app's basic example:

``` js
var yo = require('yo-yo')
var sendAction = require('send-action')

/*
* Create send function.
*/
var send = sendAction({
  onaction: onaction,
  onchange: onchange,
  state: { value: 'ok' }
})

/*
* Set up the action handler to modify state based on the actions triggered
*/
function onaction (action, state) {
  if (action.type === 'example') {
    return { value: action.value }
  }
}

/*
* Subscribe to changes to the store to render the app
*/
function onchange (action, state, oldState) {
  yo.update(document.getElementById('app'), render(state))
}

/*
* Render the html of the app with yo-yo
*/
function render (state) {
  return yo`<div id="app">${state.value}</div>`
}

/*
* Attach the html to the dom
*/
document.body.appendChild(render(send.state()))

/*
* Send an action to the store
*/
send({ type: 'example', value: 'cool' })
```

**Comment by yoshuawuyts** [comment]
Yeah, I quite like it. If we add a lil RAF as a separate thing we're where we wanna be. Neat, thanks!
