### ISSUE TITLE
use hyperx?

### ISSUE THREAD

**Issue by yoshuawuyts** [sethvincent/virtual-app#3]
https://github.com/substack/hyperx

reckon is this is used all over the place it'd be pretty good. Should it be integrated? Should it just be in examples?

**Comment by sethvincent** [comment]
Ooh I've been meaning to try that module out. 

I definitely want to show some usage examples with it. Not sure yet about making it a dependency.

**Comment by yoshuawuyts** [comment]
Yeah, on the one hand it's pretty sweet; on the other hand it's ES6. I'll give it a whirl too and let you know how it's been (':

**Comment by yoshuawuyts** [comment]
So this works pretty well, but I don't think it should be included in `virtual-app`; especially with https://github.com/substack/hyperx/issues/11 in mind
